spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sustem
    password: sustempass
    url: jdbc:h2:tcp://localhost/~/e-commerce-test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true